### ISSUE TITLE
IE11 does not popunder when there is more than one tab in the window opening the popunders.

### ISSUE THREAD

**Issue by kkirkhope** [hpbuniat/jquery-popunder#46]
In the IE11 release candidate the popunders only work if the window only has one tab open. If you have multiple tabs open and you try and one of them tried to open popunders they open as pop-ups.

I've tried using the chrome fullscreen workaround. This only works when the user has allowed IE to open in fullscreen mode.

**Comment by rszijj** [comment]
Hi,
Is somebody working on this issue?
Thanks!

**Comment by alexkrasov** [comment]
I've found out that the "popup instead of popunder" is a version-specific issue at IE11
It DOES works under 11.0.9600.17633 (popunder)
It DOESN'T under 11.0.9600.17691(popup most of the time)

**Comment by ruanmer** [comment]
any solution?

**Comment by rikius** [comment]
To make focus on IE11 with more tabs you need to use "document.focus()" instead of using this method:
t.switcher.simple(t);
