### ISSUE TITLE
Chrome 41 loads it as a new tab

### ISSUE THREAD

**Issue by darylljann** [hpbuniat/jquery-popunder#67]
With Chrome's latest update, the plugin doesn't load the tab in the background anymore

**Comment by gibigate** [comment]
```javascript
e.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, p, false, !p, p, 0, null);
```
awkward method:
add alert(); after mouseevent, tab will be return

**Comment by cpietsch82** [comment]
But this method doesn't create a new background tab on chrome 41. I need a new background tab !

**Comment by felfiz** [comment]
New update really crashed background tab.

**Comment by gibigate** [comment]
any solutions?

**Comment by adamstruve** [comment]
Also looking for a solution.

**Comment by darylljann** [comment]
thank you kind sir!
