### ISSUE TITLE
Automatic Opening

### ISSUE THREAD

**Issue by zarza** [hpbuniat/jquery-popunder#68]
Hello there,

How Can I set this Up to open a popunder after first click in any element on page?

I just want a popunder every one hour with any click in our page.

Thank you in advanced!

**Comment by adamstruve** [comment]
something like this and set the cookie to 1 hour maybe.
```javascript
$(document).click (function (event) {
pop code here
});
```

**Comment by hpbuniat** [comment]
Should work with
    $.popunder(aStack, '', 'body');
