### ISSUE TITLE
MacOs popunder opened as new tab on fullscreen mode chrome 41

### ISSUE THREAD

**Issue by gibigate** [hpbuniat/jquery-popunder#71]
Also doesn't work on click any link, only forms

MacOs  X 10.9.5
chrome 41.0.2272

**Comment by hpbuniat** [comment]
As i have no possibility to test on a Mac, I'd add it to the skip-section.

Of course, I'm open for donations ;).

**Comment by adamstruve** [comment]
On 10.10.2 with Chrome 41.0.2272 I get a pop up sometimes, pop under sometimes.  Let's get a mac in @hpbuniat hands!

**Comment by hpbuniat** [comment]
Still no mac
