### ISSUE TITLE
Load after AJAX

### ISSUE THREAD

**Issue by rafelsanso** [hpbuniat/jquery-popunder#72]
Hi all!

Very good plugin, It was very helpful!

I have a problem loading the plugin. On my site, popunders URLs are generated by AJAX. And they can be generated more than once before pressing submit the form. This causes they join the URLs and finally opens too many popunders.

What I want to know is if there is a way to reset or clear the $ .popunder function to not take the above values.

Greetings!

**Comment by hpbuniat** [comment]
Have a look at Testcase #5 - it's using a function to provide the popunder-urls at the time, when your desired event is triggered.
