### ISSUE TITLE
Upcoming Chrome Version (44) blocks the popunder functionality again

### ISSUE THREAD

**Issue by alexkrasov** [hpbuniat/jquery-popunder#76]
The upcoming version of Chrome (tested against 44.0.2400.0 canary) is blocking again the popunder functionality, the popunder is being displayed as a pop-up again (despite the flash overlay trick)...

**Comment by yoris** [comment]
The same issue with just released Chrome 43.0.2357.65

**Comment by alexkrasov** [comment]
Confirmed, the 43.0.2357.65 has this issue...

**Comment by jahanna** [comment]
On Chrome 43.0.2357.130 m the code is working but acting like a popup. How we can fix this?

**Comment by markpatx** [comment]
http://c1.popads.net/v.swf this swf is working (only when loaded from that site), but it's obfuscated as f#%k, maybe someone with more skill could take a look at it.

**Comment by rikius** [comment]
in my case it is not working. I tested it on http://mp3clan.net/

**Comment by alonbilu** [comment]
This one works well (using Flash) on chrome v45.x -->  http://popunderscript.com/

**Comment by gibigate** [comment]
what about mac fullscreen mode?

**Comment by alonbilu** [comment]
And here's another one that even managed to generate a popunder (actually a new tab) without Flash -> https://getpopunder.com/

**Comment by gibigate** [comment]
Do you have a free version of popunder?
