### ISSUE TITLE
Popunder doesn't work in Edge and chrome v49

### ISSUE THREAD

**Issue by swetha-palni** [hpbuniat/jquery-popunder#79]
with the error

Unable to get property 'target' of undefined or null reference in IE 
Cannot read property 'target' of undefined in chrome

**function callPopunder()
{
 window.aPopunder = [ ['https://in.yahoo.com/'] ];
 jQuery.popunder();
}**

here, source is always undefined for both ie and chrome.

  getFormUrl: function(**source**, bReturnIfNotBlank) {

  }

**Comment by oozrafa** [comment]
I also get this :(
I'm trying to programmatically open the popunder myself because there are extra checks which I do.

**Comment by alipour66m** [comment]
we are waiting...

**Comment by clivend** [comment]
+1

**Comment by TcPhilBushnell** [comment]
+1

**Comment by hpbuniat** [comment]
Was fixed with #81 and #82.
