### ISSUE TITLE
example does not work when <pre></pre> changed to <script></script> tags.

### ISSUE THREAD

**Issue by johnjwatson** [hpbuniat/jquery-popunder#80]
When I run the example as it is, everything seems to be working fine. However, when I change the code within the `<pre>/<pre>` blocks, to `<script></script>` nothing works anymore. I am totally confused as to why this is happening. Any help would be great.

**Comment by johnjwatson** [comment]
I also want to add that it is a bad example to run code using `eval` on `<pre>` tags. I have never seen such an approach before. It still does not work when I convert <pre> to <script> tags. Maybe my JS/jquery knowledge is limited, but I wonder how anyone has got this example to work. Any help woud be great here..

**Comment by webmisterin** [comment]
the "pre" part is what it is, a pre part. to show the code pre-formated if u open the example.html with a browser. so no need to change pre to script. the script part is included after the pre part.. ;)

**Comment by hpbuniat** [comment]
Thanks @webmisterin
